spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cambridgeDB
    username: postgres
    password: examplepassword

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false


